
export const environmentServed = {
	appKey: '8b0cae93d47a44e48e97e7fd0404be4e',
	channelName: 'BHere',
	flags: {
		production: true,
		useProxy: false,
		useToken: false,
		selfService: true,
		guidedTourRequest: true,
		editor: false,
		editorAssetScreen: false,
		ar: true,
		menu: true,
		chat: false,
		attendee: true,
		streamer: true,
		viewer: true,
		smartDevice: true,
		maxQuality: false,
	},
	logo: null,
	background: {
		image: '/Modules/more/Client/docs/img/background.jpg',
		video: '/Modules/more/Client/docs/img/background.mp4',
	},
	colors: {
		menuBackground: '#000000',
		menuForeground: '#ffffff',
		menuOverBackground: '#0099ff',
		menuOverForeground: '#ffffff',
		menuBackBackground: '#0099ff',
		menuBackForeground: '#000000',
		menuBackOverBackground: '#0099ff',
		menuBackOverForeground: '#ffffff',
	},
	editor: {
		disabledViewTypes: ['waiting-room', 'room-3d'],
		disabledViewItemTypes: ['texture'],
	},
	assets: '/Modules/more/Client/docs/',
	worker: '/Modules/more/Client/docs/js/workers/image.service.worker.js',
	githubDocs: 'https://raw.githubusercontent.com/actarian/more/more-ws-new/docs/',
	language: '/it',
	market: '/it',
	url: {
		index: '/',
		access: '/',
		editor: '/editor',
		selfServiceTour: '/self-service-tour',
		guidedTour: '/guided-tour',
		accessCode: '/access-code',
	},
	template: {
		tryInAr: '/template/modules/more/try-in-ar.cshtml?viewId=$viewId',
		modal: {
			controlRequest: '/template/modules/more/control-request-modal.cshtml',
			tryInAr: '/template/modules/more/try-in-ar-modal.cshtml',
			view: {
				'panorama': '/template/modules/more/panorama-modal.cshtml',
				'panorama-grid': '/template/modules/more/panorama-grid-modal.cshtml',
				'room-3d': '/template/modules/more/room-3d-modal.cshtml',
				'model': '/template/modules/more/model-modal.cshtml',
			},
			viewItem: {
				'nav': '/template/modules/more/nav-modal.cshtml',
				'plane': '/template/modules/more/plane-modal.cshtml',
				'curved-plane': '/template/modules/more/curved-plane-modal.cshtml',
				'texture': '/template/modules/more/texture-modal.cshtml',
				'model': '/template/modules/more/item-model-modal.cshtml',
			},
			remove: '/template/modules/more/remove-modal.cshtml',
		}
	},
	languages: ['en'],
	defaultLanguage: 'en',
};
